import numpy as np

print(f"\n= max, argmax =================")
array = np.random.randint(30, size=(3, 5))
print(f"INPUT ARRAY : \n{array}\n")
print(f"Max Element: array[{np.argmax(array)}] = {np.max(array)}\n")
print(f"[Axis=0]")
print(f"\tIndices of Max element: {np.argmax(array, axis=0)}")
print(f"\tValues of Max element:  {np.max(array, axis=0)}")
print(f"[Axis=1]")
print(f"\tIndices of Max element: {np.argmax(array, axis=1)}")
print(f"\tValues of Max element:  {np.max(array, axis=1)}")
a1 = np.random.randint(10, size=(2, 2))
a2 = np.random.randint(10, size=(2, 2))
a3 = np.random.randint(10, size=(10))
print(f"\n= maximum =====================")
print(f"INPUT ARRAY 1: \n{a1}\n")
print(f"INPUT ARRAY 2: \n{a2}\n")
print(f"Maximum of Array 1 and 2: \n{np.maximum(a1, a2)}\n")
print(f"INPUT ARRAY 3: \n{a3}\n")
print(f"Accumulated Maximum of Array 3: \n{np.maximum.accumulate(a3)}")
